const catalog=[
['Debt Collection Removal Package','$225','A focused service for consumers who want help addressing collection accounts appearing on their credit report. The process is designed to review the account information, identify items that may warrant a dispute or follow-up, and help organize the appropriate next steps.',['Review collection-account information','Identify potentially inaccurate, incomplete, or questionable reporting','Prepare and organize the information needed for the dispute process','Discuss follow-up steps based on the response received'],'Individual collection accounts and results vary by credit profile and documentation.'],
['Remove Hard Inquiries','$125','A service for consumers who want to review hard inquiries on their credit report, particularly inquiries they believe may be inaccurate or unauthorized.',['Review the hard inquiries appearing on the report','Identify inquiries the consumer believes may be inaccurate or unauthorized','Organize relevant information for a dispute or follow-up','Discuss the next steps after the inquiry is reviewed'],'Only inquiries that are inaccurate, unauthorized, or otherwise disputable should be challenged.'],
['4 Month Program','$400','A four-month credit-support program built around four rounds of disputes and ongoing follow-up. It is intended for consumers who need more than a single dispute round and want a structured process over several months.',['Four rounds of dispute activity during the program','Review and address eligible negative or questionable items','Track responses and determine appropriate follow-up','Structured support throughout the four-month period'],'The exact items addressed depend on the consumer’s credit reports and supporting documentation.'],
['3B Expedited Service / 1 Round Aggressive Disputes','$500','An expedited service option for consumers who want a focused first round of disputes handled on a shorter service timeline. The package is designed for a concentrated review and dispute cycle rather than a multi-month program.',['Focused review of the consumer’s credit-report concerns','One concentrated round of eligible disputes','Expedited handling of the service request','Follow-up discussion after responses are received'],'Expedited service does not guarantee a particular deletion, score increase, or outcome.'],
['4 Month Program / Payment Plan','$200','A four-month program offered with a payment-plan structure for consumers who want ongoing credit-support services while spreading the program cost across monthly payments.',['Four months of structured credit-support services','Multiple dispute rounds as applicable to the account review','Ongoing review and follow-up during the program','Monthly payment-plan structure'],'Program eligibility, payment terms, and the specific items addressed should be confirmed with the business before starting.'],
['Expedited Debt Collection Package','$300','An expedited package for consumers who specifically want to address collection accounts on their credit report. It is designed for a more focused collection-account review and service process.',['Review collection accounts reported on the credit profile','Identify potentially inaccurate or disputable information','Prepare the relevant dispute or follow-up information','Expedited service and communication regarding the request'],'Collection-account outcomes depend on the accuracy of the reporting and the documentation available.'],
["Couple's Package / 4 Month Program",'$700','A four-month program designed for couples who want to work on their credit-support needs together. Each person’s credit profile is reviewed separately because credit reports and circumstances can differ between individuals.',['Four-month program structure for two people','Individual review of each person’s credit-report concerns','Dispute and follow-up support based on each profile','Coordinated communication for the couple’s service'],'Each person’s results are individual and depend on their own credit reports, documentation, and circumstances.']
];
const q=new URLSearchParams(location.search),requested=q.get('plan')||'General Credit Repair Inquiry',selected=catalog.find(x=>x[0]===requested),name=selected?selected[0]:requested,price=selected?selected[1]:'';document.getElementById('selectedPlan').textContent=name;document.getElementById('selectedPrice').textContent=price;
if(selected){document.getElementById('detailTitle').textContent=selected[0];document.getElementById('detailDescription').textContent=selected[2];document.getElementById('detailPoints').innerHTML=selected[3].map(x=>`<div class="detail-point"><span>✓</span><p>${x}</p></div>`).join('');document.getElementById('detailNote').textContent=selected[4];}else{document.getElementById('detailDescription').textContent='Contact the team to discuss your credit concerns and determine which service may be appropriate for your situation.';document.getElementById('detailPoints').innerHTML='';}
const message=`Hello, I would like to inquire about the ${name}${price?` (${price})`:''}.\n\nPlease provide me with the next steps and any information you need from me to get started.\n\nThank you.`;document.getElementById('messagePreview').textContent=message;document.getElementById('telegramBtn').href=`https://t.me/${SITE_CONFIG.telegramUsername}?text=${encodeURIComponent(message)}`;const email=document.getElementById('emailBtn');if(SITE_CONFIG.email&&SITE_CONFIG.email!=='YOUR_EMAIL_HERE')email.href=`mailto:${SITE_CONFIG.email}?subject=${encodeURIComponent('CreditRepair.US Inquiry – '+name)}&body=${encodeURIComponent(message)}`;else{email.href='#';document.getElementById('emailWarning').hidden=false;email.onclick=e=>e.preventDefault();}